import type { Metadata,Viewport } from "next";
import "./globals.css";
import Providers from "@/redex/Providers";


export const metadata: Metadata = {
  title: "Minecraft Aditya",
  description: "Generated by Aditya Aryan",
};

export const viewport: Viewport={
  width:"device-width",
  userScalable:false,
  initialScale:1
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
        {children}
        </Providers>
        </body>
    </html>
  );
}
